const types = {
  LOAD_PROJECTS: 'LOAD_PROJECTS',
  PROJECTS_LOADED: 'PROJECTS_LOADED',
  LOAD_PROJECTS_ERROR: 'LOAD_PROJECTS_ERROR',

  ADD_PROJECT: 'ADD_PROJECT',
  PROJECT_ADDED: 'PROJECT_ADDED',
  ADD_PROJECT_ERROR: 'ADD_PROJECT_ERROR',

  DELETE_PROJECT: 'DELETE_PROJECT',
  PROJECT_DELETED: 'PROJECT_DELETED',
  DELETE_PROJECT_ERROR: 'DELETE_PROJECT_ERROR',
};

export default types;
