const types = {
  LOAD_PATH_NAMES: 'LOAD_PATH_NAMES',
  PATH_NAMES_LOADED: 'PATH_NAMES_LOADED',
  LOAD_PATH_NAMES_ERROR: 'LOAD_PATH_NAMES_ERROR',

  LOAD_PERFORMANCE_DATAS: 'LOAD_PERFORMANCE_DATAS',
  PERFORMANCE_DATAS_LOADED: 'PERFORMANCE_DATAS_LOADED',
  LOAD_PERFORMANCE_DATAS_ERROR: 'LOAD_PERFORMANCE_DATAS_ERROR',

  CLEAR_STATE: 'CLEAR_STATE',
};

export default types;
